apiVersion: apps/v1
#db should not be created using Deployment, instead using Stateful, so db often hold outside kubernetes
#here just a simple example
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
#    identify a set of resources, match all pods with the matchLabels(here mysql)
    matchLabels:
      app: mysql
  template:
    metadata:
#      labels is a required field for pods, replica pods share the same label but different names
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0-debian
          ports:
            - containerPort: 8080
          env:
            - name:
              value:

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app.kubernetes.io/name: mysql
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 8080